### PR TITLE
Make Mod Manager not rely on an extracted game when building.

### PR DESCRIPTION
**Pull request by TopazTK**
Simple as that. Make the Mod Manager build the mods and patch them in without needing an extracted game data. Because requiring the end user to extract ~25GB worth of data is plain dumb. The option to extract the game is still present for stuff that may need it, as well as for mod creators.

### CODE REVIEW

**Comment by TopazTK** [comment]
Ignore MemorySharp and Hypervisor. Those are from a previous accepted PR. Github is dumb.

**Review by shananas — COMMENTED** [review]
I see no issues in testing builds. with mods that heavily utilize OpenKh methods like KH2 Randomizer GoA ROM that mod alone takes about 1:10 to build with no extraction vs 20 seconds with an extraction. The nice thing in the case of GoA ROM since it edits so many files mods that come after doing similar things might not need to pull from non extracted files. in my testing for my randomizer setup GoA
```
no extraction 2 mins with GoA 1:10 and num cutscene skipper ~35 seconds
with extraction ~30 seconds with GoA ~20 and cutscene skipper ~6 
with M.2 gen 4 ssd and DDR4 RAM 
```
I see this as valuable and approve

**Comment by TopazTK** [comment]
> I see no issues in testing builds. with mods that heavily utilize OpenKh methods like KH2 Randomizer GoA ROM that mod alone takes about 1:10 to build with no extraction vs 20 seconds with an extraction. The nice thing in the case of GoA ROM since it edits so many files mods that come after doing similar things might not need to pull from non extracted files. in my testing for my randomizer setup GoA
> 
> ```
> no extraction 2 mins with GoA 1:10 and num cutscene skipper ~35 seconds
> with extraction ~30 seconds with GoA ~20 and cutscene skipper ~6 
> with M.2 gen 4 ssd and DDR4 RAM 
> ```
> 
> I see this as valuable and approve

Yea, I can see the speed can be a variable factor, as I have been getting speedups with different mods. However, that being said, the end user won't want to waste 10GB min / 80GB max space for the sake of a speed increase. Since both options are supported here, it should not cause any issues.

However, I will add text stating the differences.

**Review by osdanova — APPROVED** [review]
It seems to work fine. Not needing to extract the game is great IMO. Good job!

**Comment by TopazTK** [comment]
@Vladabdf stated he won't be able to make a review. A week has been allocated for testing and as a grace period.

**Comment by Vladabdf** [comment]
> week has been allocated for testing and as a grace period.

Please stop imposing arbitrary time limits to pull requests and issues.

**Comment by TopazTK** [comment]
> > week has been allocated for testing and as a grace period.
> 
> Please stop imposing arbitrary time limits to pull requests and issues. Edit: It's also a draft and cannot be merged anyway.

It will stay a draft for the given time as it is ready. The "grace period" is for the third party mods to adjust accordingly. It isn't arbitrary, it's necessary.

**Comment by Vladabdf** [comment]
That is completely arbitrary. Mods that may need to adjust (which are...?) can do so with or without the merge. If the mod authors or users can't or don't want the feature, they can use it, as it is entirely optional, right?

**Comment by TopazTK** [comment]
Closing, will not be maintained.

**Pull request closed without merging**
