### PR TITLE
PC support for Mods Manager

### PR DESCRIPTION
**Pull request by Xeeynamo**
I almost forgot about this branch and I am sorry to not have pushed this earlier. This contains an early support for the Mods Manager to support both Kingdom Hearts II and Birth By Sleep for the Epic Games release. Last commit was early April. BBS support was a bit clunky if I recall correctly and KH2 support was working for the majority of it.

The reason why I did not push it earlier is because I wanted to research on how to override HD textures but I never had the change to look into it. Please be free to use this as a base to give it a better shape if you are interested on make it working on PC.

The logic behind it it's pretty simple. `OpenKh.Research.Panacea` is supposed to patch the game's executable on the fly (eg. it will not modify the actual game's files) but you need to compile the DLL, rename it into `DINPUT8.DLL` and place it in the same folder where all the games are. There is a work in progress commit that is supposed to give OpenKH Mods Loader the possibility to add or remove this `DINPUT8.DLL` based if the user wanted or not use the mods.

If you have any question, this PR is a good place to remain in touch. Thanks to @Delta-473 to make me remind this branch I created.

### CODE REVIEW

**Comment by snelson3** [comment]
Thanks a lot for pushing this, Tommadness and I are working on finishing it up. We have one question so far:

The panacea library has a couple hardcoded base paths, IE 

` const char BasePath[] = "C:/hd28/EPIC/juefigs/KH2ReSource/"`

We changed all the places where this path exists in the openkh codebase, but when we build and launch the game it still tries to load from this path. We just made this path in our computer exist, and the modloader works, but do you know why it's still loading the hardcoded path?

```
Executable instance at 00007FF7C9A30000
Kingdom Hearts II detected.
Axa::CFileMan::LoadFile hooked to 0000025DA6B40000 successfully!
Axa::CFileMan::GetFileSize hooked to 0000025DA6D30000 successfully!
Welcome to OpenKH Panacea!
C:/hd28/EPIC/juefigs/KH2ReSource/00objentry.bin
C:/hd28/EPIC/juefigs/KH2ReSource/00objentry.bin
```

**Comment by Rikux3** [comment]
`C:/hd28/EPIC/juefigs/KH2ReSource/` is used by the game itself iirc

**Comment by Xeeynamo** [comment]
> Thanks a lot for pushing this, Tommadness and I are working on finishing it up. We have one question so far:
> 
> The panacea library has a couple hardcoded base paths, IE
> 
> ` const char BasePath[] = "C:/hd28/EPIC/juefigs/KH2ReSource/"`
> 
> We changed all the places where this path exists in the openkh codebase, but when we build and launch the game it still tries to load from this path. We just made this path in our computer exist, and the modloader works, but do you know why it's still loading the hardcoded path?
> 
> ```
> Executable instance at 00007FF7C9A30000
> Kingdom Hearts II detected.
> Axa::CFileMan::LoadFile hooked to 0000025DA6B40000 successfully!
> Axa::CFileMan::GetFileSize hooked to 0000025DA6D30000 successfully!
> Welcome to OpenKH Panacea!
> C:/hd28/EPIC/juefigs/KH2ReSource/00objentry.bin
> C:/hd28/EPIC/juefigs/KH2ReSource/00objentry.bin
> ```

Does using `C:/hd28/EPIC/juefigs/KH2ReSource` actually overrides the game's data even without Panacea?? If that's really the case then it's a neat discovery lol.
The function `Panacea::LoadFile`, which is supposed to overwrite `Axa::CFileMan::LoadFile` is supposed to replace `C:/hd28/EPIC/juefigs/KH2ReSource/` with the custom assets. The logic of it is found in `Panacea::TransformFilePath`. The path is hardcoded to be `D:\\Hacking\\openkh_mods\\mod` as it was the one I had in my computer. But what you really want to do is to read `config.yml` when Panacea DLL is loaded to get the `modPath` from there. Ideally you might be able to do it easily by setting the working directory to where the `config.yml` is located when you launch the game from the Mods Manager.

I am very, very happy that the both of you are looking at implementing this 😄 I am sure you will get it working smoothly in a few!

**Comment by MainMemory** [comment]
Just posting a comment to confirm that this is now truly ready to be merged.

**Comment by Delta-473** [comment]
Before this is merged can someone run the tests locally to see if they pass?

**Comment by TopazTK** [comment]
Seems like #644 somehow broke this.

**Review by Delta-473 — APPROVED** [review]
I want to thank everybody who worked on this feature and tested it. <3
*There are probably some hidden little features here and there but that's to be changed after this*

**Pull request merged**
