### PR TITLE
Add to worlds.md

### PR DESCRIPTION
**Pull request by Oathseeker**
Added World Location Area names: 
Credit should largely go to Murugo for his Kingdom Hearts Map Viewer 0.1.5 program clearly listing the location names of the ,bin files, I just compiled it into a list for openkh :)

### CODE REVIEW

**Comment by Truthkey** [comment]
Looks perfectly fine, but I'd like some changes before merging if you don't mind.

1. Create a list with all the world with a World ID and World Name section for each.

EXAMPLE:

World ID     World Name
TZ               Deep Jungle
ZZ                Debug

2. Make the list be hyperlinks that take you to the world section.
3. Use official names for the rooms if available. If not available, put them in another column.

For reference, check out the BBS world.md at [this link](https://github.com/Xeeynamo/OpenKh/blob/master/docs/bbs/dictionary/worlds.md).

**Comment by Oathseeker** [comment]
> Looks perfectly fine, but I'd like some changes before merging if you don't mind.
> 
>     1. Create a list with all the world with a World ID and World Name section for each.
> 
> 
> EXAMPLE:
> 
> World ID World Name TZ Deep Jungle ZZ Debug
> 
>     2. Make the list be hyperlinks that take you to the world section.
> 
>     3. Use official names for the rooms if available. If not available, put them in another column.
> 
> 
> For reference, check out the BBS world.md at [this link](https://github.com/Xeeynamo/OpenKh/blob/master/docs/bbs/dictionary/worlds.md).

Cool, ill make the adjustments, thanks key :)

**Comment by Delta-473** [comment]
What is the state on this pr? :)

**Review by Vladabdf — APPROVED** [review]
Approved. It's largely finished. Edits can always be made later.

**Pull request merged**
