### PR TITLE
Added listpatch support for LVPM

### PR DESCRIPTION
**Pull request by kareking1**
Made Lvpm listpatchable. This solution should be applicable for all files that don't have an ID. Also had to include a new class in BaseTable to account for tables that only have 1 int as a header and not 2 ints...

### CODE REVIEW

**Comment by kareking1** [comment]
Correction: The new class is for when there is no header at all

**Review by shananas — CHANGES_REQUESTED** [review]
You also need to write a test for this in OpenKh.Tests/Patcher/PatcherTests.cs
and write documentation in docs/tool/GUI.ModsManager

**Comment by kareking1** [comment]
> You also need to write a test for this in OpenKh.Tests/Patcher/PatcherTests.cs and write documentation in docs/tool/GUI.ModsManager/creatingMods.md

I added a working test and an entry to lvpm. Let me know if there's anything else

**Comment by shananas** [comment]
youll need to sync changes since your PR as your adding back a removed .yml and seemingly editing some submodules. hopefuly this also fixes the build error as its unrelated to your code changes.

**Comment by kareking1** [comment]
> youll need to sync changes since your PR as your adding back a removed .yml and seemingly editing some submodules. hopefuly this also fixes the build error as its unrelated to your code changes.

I'm not sure what to do about the submodules. I deleted the yml file, but I can't do anything about them... kinda just automatic. I can delete them using git rm, but idk if you want me to straight remove them

**Pull request closed without merging**
