### PR TITLE
Implement downloader and updater on client side

### PR DESCRIPTION
**Pull request by kenjiuno**
up2

### CODE REVIEW

**Comment by kenjiuno** [comment]
ok this will be ready

**Comment by TopazTK** [comment]
Maybe we should not reset the configuration upon update, and change the text in the window to say "Updating" instead of "Downloading Mod OpenKH"

**Comment by kenjiuno** [comment]
I'll fix

**Comment by kenjiuno** [comment]
This'll be better

**Comment by TopazTK** [comment]
Everything looks good on the code side. Needs testing.

**Review by shananas — APPROVED** [review]
Works on my end too. I'll merge tomorrow if no one else does

**Pull request merged**
