### PR TITLE
Panacea: Fixing Gummi crash, implementing BASS_VGMStream for KH2 titl…

### PR DESCRIPTION
**Pull request by MainMemory**
…e/results/gummi music.

I did not modify the build process at all. All the DLL files in the OpenKh.Research.Panacea/Dependencies folder need to be copied to the build, as well as being copied into the game's folder alongside the Panacea DLL (DBGHELP.DLL).

### CODE REVIEW

**Review by TopazTK — CHANGES_REQUESTED** [review]
Based. Requesting @Vladabdf for a legal review.

**Comment by Vladabdf** [comment]
Has it been tested? @TopazTK

**Comment by TopazTK** [comment]
@Vladabdf I am a dumb-dumb and cannot build this. I fully anticipate that @MainMemory has tested this through and through, and realize that someone else will have to as the build scriot needs editing anyways.

**Comment by shananas** [comment]
I plan on updating mod manager for this and testing it I asked about possible loading the extra dlls from a subfolder as to not bloat the game install bug that'd be a nice to have. I plan on testing soon myself and updating mod manager also

**Comment by MainMemory** [comment]
Yeah I tested it, it seems to work properly, more or less.

**Comment by shananas** [comment]
It should be known this should be merged with a Mod Manager update as according to #developers-only if the extra .dlls are not copied it will crash. I should be able to put it together tomorrow but if someone else wishes to make the changes before then to mod manager so they can be merged together I'm fine with that

**Review by shananas — APPROVED** [review]
LGTM merge after #862 so mod manager has proper error handling and the game does not crash because its missing dependencies

**Review by TopazTK — APPROVED** [review]
Based.

**Pull request merged**
