### PR TITLE
OpenKh.Tools.Kh2MsetMotionEditor

### PR DESCRIPTION
**Pull request by kenjiuno**
## Screen shot

2023-11-06_19h49_55

Kh2MsetMotionEditor is a low level mset motion editor.

In low level meaning, this can edit the _value_ of the following tables listed at the site documentation: https://openkh.dev/kh2/file/anb/motion.html

- IKHelper
- InitialPose
- Expression
- Constraint
- Joint
- FCurvesForward
- FCurvesInvese
- FCurveKey
- RootPosition

Also this can export tables to (also import tables from) Excel `.xlsx` file.

The realtime motion previewer is also equipped.

### keyboard short cuts

Key | work
---|---
`W` | forward
`S` | back
`A` | left
`D` | right
`Q` | up
`E` | down

It is same as map studio.

## Customization 

For fun with this ~crazy~ motion editor, there are some cool features to make it smarter.

### `Kh2Presets/BoneDict.xml`

Define about bones.
Bones manager and model renderer will **display** them.

`Name`: At bone manager
`SpriteIcon`: At model renderer. 0 to 255. 0 is invisible. 255 is used for selected bone.

```xml
<BoneDict>
    <BoneView Match="p_ex100;">
        <Bone I="0" Name="Root" SpriteIcon="1" />
        <Bone I="1" Name="Pt1" />
        <Bone I="5" Name="Pt5" SpriteIcon="2" />
    </BoneView>
    <BoneView Match="p_ex100,a000">
        <Bone I="228" Name="IKRoot" />
    </BoneView>
</BoneDict>
```

Initial sprite icons from MS Webdings font.

SpriteIcons

Numbered

### `Presets.xml`

Load the mdlx/mset files quickly.
Used at Tools window.

2023-11-06_20h01_32

```xml
<Presets>
    <Preset Label="Sora"
        Mdlx="P_EX100.mdlx"
        Mset="P_EX100.mset"
        AutoLoad="true"
        DefaultMotion="6" />
    <Preset Label="Sora ETT00101E"
        Mdlx="P_EX100.mdlx"
        Mset="tt\p_ex100\ETT00101E.anb"
        AutoLoad="true"
        DefaultMotion="0" />
    <Preset Label="Sora EHB20601E"
        Mdlx="P_EX100.mdlx"
        Mset="tr\p_ex100\EHB20601E.anb"
        AutoLoad="true"
        DefaultMotion="0" />
    <Preset Label="Roxas"
        Mdlx="P_EX110.mdlx"
        Mset="P_EX110.mset"
        AutoLoad="true"
        DefaultMotion="2" />
</Presets>
```

### `Kh2Presets` folder

Dig `Kh2Presets` folder under the application folder.
`Kh2Presets` folder is separated so that we can make it easily git repository in order to share or backup the configs.

2023-08-02_21h06_33

### Reload Kh2Presets

You can reload xml files on demand.

image

## IMEx (import and export) Excel xlsx

For advanced low level value editing, you can export their values into excel files.

image

### Bones

Display FK and IK bones.

image

Use `BoneDict.xml` to attach sprite icon and label.

### IKHelper

Internally both FK bones and IK bones share same structure. However due to OpenKh internal issue, FK cannot be edited for now.

FK

image

IK

image

### InitialPose

image

### Expression

image

### Constraints

2023-07-30_22h21_13

### PrintDebugInfo

image

### Joint

The term joint and bone are confusing. Joint may mean bone.

image

### FCurvesForward / FCurvesInverse

Both FCurvesForward and FCurvesInverse share same format.

image

### FCurveKey

image

### RootPosition

2023-11-06_20h07_25

## Architecture

There is memo level info about how this editor has been designed.

### Using DI

This uses `Microsoft.Extensions.DependencyInjection` for IoC/DI.

See also:

- [Dependency injection - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection)

This DI engine's usage is simple like this:

```cs
void Runner()
{
    var builder = new ServiceCollection();
    builder.AddSingleton<MonoGameImGuiBootstrap>();
    // ...

    using var container = builder.BuildServiceProvider();

    var bootstrap = container.GetRequiredService<MonoGameImGuiBootstrap>();

    bootstrap.Run();
}
```

This kind of DI engine provides _constructor injection_.
This is helpful if there are many dependencies on the use case.

2023-11-06_20h31_32

### Usecases

I write most business logics to _use cases_ that has `Usecase` to suffix in its C# class name.

There are plenty of use case classes.

2023-11-06_20h20_49

Rarely, there are some interface like use cases.

```cs
namespace OpenKh.Tools.Kh2MsetMotionEditor.Usecases
{
    public delegate Texture2D CreateSpriteIconsTextureUsecase();
}
```

In such case the implementation is defined at DI builder.

```cs
self.AddSingleton<CreateSpriteIconsTextureUsecase>(
    sp =>
        () =>
        {
            return sp.GetRequiredService<ContentManager>().Load<Texture2D>("SpriteIcons");
        }
);
```

In my policy, any use case _shoudn't_ have _mutable state_ inside it.
In other word do not place _data_ to _use case_.

Some reasons:

- The use case may be altered and disposed in any reasons. In this case, _data_ should be ejected to outside use case, at last.
- The _data_ in the _use case_ is difficult to share with 2 or more use cases.
- If the use case acts stateful objects like `FileStream` or `Form`, it is hell to maintainers.

This is a bad case. ✘. If `CounterUsecase` is disposed, where the _counter_ goes?

```cs
class CounterUsecase
{
    private int _counter = 0;

    public void Increment()
    {
        _counter++;
    }

    public int GetCounter() => _counter;
}
```

This is preferred. ☑. Even if `CounterUsecase` is disposed, `CounterEngine` is still alive and functionary is kept.

```cs
class CounterUsecase
{
    private readonly CounterEngine _counter;

    public CounterUsecase(CounterEngine counter)
    {
        _counter = counter;
    }

    public void Increment() => _counter.Increment();

    public int GetCounter() => _counter.GetCounter();
}
```

This is also possible alternative. ☑. Using _lambda expression_ and _captured variables_ will continue to keep use case _stateless_.

```cs
class CounterUsecase
{
    public CounterUsecase()
    {
    }

    public Func<int> CreateIncrementalCounter()
    {
        int count = 0;

        return () =>
        {
            return ++count;
        };
    }
}
```

### Settings.settings

Open `Settings.settings` and then add boolean flag to mean visible/invisible.

2023-11-06_21h18_00

### new class

Create new class file under `Usecases/ImGuiWindows` like `RootPositionWindowUsecase.cs`

Inherites `IWindowRunnableProvider`, and also add `CreateWindowRunnable` method.

This prototype may help:

```cs
private readonly Settings _settings;

public RootPositionWindowUsecase(
    Settings settings
)
{
    _settings = settings;
}

public Action CreateWindowRunnable()
{
    return () =>
    {
        if (_settings.ViewRootPosition)
        {
            var windowClosed = !ForWindow("RootPosition", () =>
            {
                // ...
            },
                menuBar: false
            );

            if (windowClosed)
            {
                _settings.ViewRootPosition = false;
                _settings.Save();
            }
        }
    };
}
```

Write the windowing logic inside lambda of `ForWindow` method.

### Register to DI

Open `DependencyInjection/UseExtensions.cs`.

Add the declaration around `// windows` area.

```cs
// windows
// ...
self.AddSingleton<IWindowRunnableProvider, RootPositionWindowUsecase>();
```

The registration order is important.
The every window is rendered in the order `AddSingleton` is placed.

### Adding mutable state

The most mutable states are aggregated to single class `Helpers/LoadedModel.cs`.

### pub/sub

If light weight pub/sub pattern is needed, these are available. But they are not event driven. Loop driven is assumed.

#### AgeManager

```cs
public AgeManager SelectedJointIndexAge { get; set; } = new AgeManager();
```

```cs
_loadedModel.SelectedJointIndexAge.Bump();
```

```cs
var scrollAge = _loadedModel.SelectedJointIndexAge.Branch(false);

return () =>
{
  // ...
  var needToScroll = scrollAge.NeedToCatchUp();
  // ...
};
```

#### OneTimeOn

```cs
public OneTimeOn SendBackMotionData { get; set; } = new OneTimeOn(false);
```

```cs
_loadedModel.SendBackMotionData.TurnOn();
```

```cs
if (_loadedModel.SendBackMotionData.Consume())
{
  // ...
}
```

### OpenKh.Engine/MathEx.cs

Adding MathEx.Modulus

### OpenKh.Kh2/CodeGenerators/CodeGen.cs

Fixed wrong bit positioning.

### OpenKh.Kh2AnimEmu/Mset/EmuBasedAnimMatricesProvider.cs

`ProvideMatrices2(...)` get IK bones matrix.
`ResetGameTimeDelta()` reset time to zero, advanced by `ProvideMatrices2(double gameTimeDelta)`

### OpenKh.Kh2AnimEmu/Mset/EmuRunner/Mlink.cs

`ee.mset.ram.bin.gz` is now embedded inside resource.

### OpenKh.Tools.Common.CustomImGui/ImGuiEx.cs

`ForWindow` +menuBar arg
`ForHeader` +openByDefault arg
`ForEdit4` new
`ForCombo` new

### CODE REVIEW

**Review by Vladabdf — COMMENTED** [review]
The legacy (and hopefully soon to be deprecated) mset editor that has been used outside of OpenKH for years is able to call PAX and DPD, and even WD sound effects per-frame. I am not extremely familiar with this older tool as most of my mod experience comes from textures and layout data, but I wish to know, is that an intended addition to this tool?

This is looking very nice so far regardless. I hope many people get a lot of use from this and the new MDLX editor!

**Comment by kenjiuno** [comment]
Finally, the excitement subsided and I calmed down.

Frankly speaking, I'm thinking to rename this from _Kh2MsetEditorCrazyEdition_ to _Kh2MsetMotionEditor_.

For now I have no interest about [trigger](https://openkh.dev/kh2/file/anb/anb.html#motion-triggers) data and so on.
At motion data format, the main thing I wanted to know was how _Expressions_ (and ExpressionNodes) and _Constraints_ (, ConstraintActivations and Limiters) data are represented in ANB file.
The visualization succeeded anyway so I'm satisfied in a sense.

**Comment by Vladabdf** [comment]
Is this pull request ready to merge?

**Comment by kenjiuno** [comment]
This will be ready 👍

**Review by Vladabdf — APPROVED** [review]
Very exciting!

**Pull request merged**
