### PR TITLE
Update logo to something simpler and honestly better

### PR DESCRIPTION
**Pull request by Vladabdf**
Title.
Very smol.
Pls no h8.

### CODE REVIEW

**Review by kenjiuno — APPROVED** [review]

**Comment by shananas** [comment]
I like both versions personally might prefer the old one since im not that into simple icons but if others like the new one im for it. crown show up more rather than wayfinders.

**Comment by TopazTK** [comment]
I personally do not like either of them. But that is just me.
Thusforth, I have no input.

**Comment by Vladabdf** [comment]
@TopazTK Input after the change?

**Comment by TopazTK** [comment]
@Vladabdf The align of "KH" to "Open" bothers my OCD, but besides that, the new logo is 🔥

**Review by TopazTK — APPROVED** [review]
Based.

**Pull request merged**
